Name=zero-lliurex-pmb
Name[en]=PMB Installer
Name[es]=PMB, gestor de la biblioteca
Name[qcv]=PMB, gestió de la biblioteca
Name[ca_ES]=PMB, gestió de la biblioteca
Comment=PMB installer
Comment[en]=PMB installer in any lliurex flavor
Comment[es]=Instalador del gestor de bibliotecas en servidores
Comment[qcv]=Instal·lador del gestor de biblioteques en servidors
Comment[ca_ES]=Instal·lador del gestor de biblioteques en servidors
Icon=zero-lliurex-pmb
Category=Services
ScriptPath=zero-lliurex-pmb.zmd
Groups=sudo;admins
Using=pkexec
Service=True
Modal=True
Locks=zero-lliurex-pmb
