#!/bin/bash


ACTION="$1"

case $ACTION in

	preInstall)
	
		#docker pull lliurex/lliurex-pmb
	;;	

	postInstall)
		echo "Testing it MySQL is alive and the root passwd is available..."
		sudo mysql_root_passwd -i

		echo "Checking if pmb database exists..."
		lliurex-sgbd --db_is_present lliurex-pmb
		if [ ! -f /tmp/db_is_present ]; then
			echo "Creating PMB database..."
			lliurex-pmb --install-database
		else
			echo "PMB database are going to update..."
			lliurex-pmb --upgrade
		fi

		echo "Configuring PMB hosts..."
		lliurex-pmb --hosts

		check_container=$(docker ps -a -f name=pmb | grep "pmb" | cut -d  " " -f 1)
		
		if [ -z "$check_container" ]; then
			echo "Downloading and starting pmb docker ..."
			docker run -d --restart always --name pmb -v /usr/share/pmb/www:/var/www/html -v /var/lib/pmb:/var/lib/pmb -v /etc/pmb:/etc/pmb -v /var/run/mysqld:/var/run/mysqld -p 800:80 lliurex/pmb_base
		
			check_download=$(docker images lliurex/pmb_base -q)
			if [ -z "$check_download" ]; then
				echo "Unable to download pmb docker"
				exit 1
			fi

			check_docker=$(docker ps -f name=pmb | grep "pmb" | cut -d  " " -f 1)
			if [ -z "$check_docker" ]; then
				echo "Unable to start pmb docker"
				exit 1
			fi

		fi
		
	;;
	remove)

		apt-get purge -y lliurex-pmb
		TEST=$( dpkg-query -s  lliurex-pmb 2> /dev/null| grep Status | cut -d " " -f 4 )
		if [ "$TEST" == 'installed' ];then
			exit 1
		fi
				
	;;	
esac